name: Publish Docker

on:
  push:

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUBNAME }}
          password: ${{ secrets.DOCKERHUBPWD }}
          repository: excalidraw/excalidraw-room
          tag_with_ref: true
          tag_with_sha: true
